### ISSUE TITLE
Not working on 1.12

### ISSUE THREAD

**Issue by dadee971** [Blackvein/Quests#523]
Hi,
Quests is not working on Spigot 1.12.
`[15:15:50] [Server thread/INFO]: [Quests] Enabling Quests v2.7.6-b121
[15:15:50] [Server thread/INFO]: [Quests] Config not found, writing default to file.
[15:15:50] [Server thread/ERROR]: Error occurred while enabling Quests v2.7.6-b121 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.FileConfiguration.load(Ljava/io/InputStream;)V
	at me.blackvein.quests.Quests.defaultConfigFile(Quests.java:303) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:185) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

**Comment by FlyingPikachu** [comment]
@dadee971 Just pushed an untested 1.12 commit https://github.com/Blackvein/Quests/commit/7ef239ba4f541ac8335e80dfcda3bb4280a02748

Dev build should be available on Jenkins soon (assuming downloads are fixed). If not, you'll have to wait a bit for me to test it. Thanks!
